/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105336-g7247a6fed8-20220121"
#endif /* AVUTIL_FFVERSION_H */
